# Generated by Django 5.2.11 on 2026-02-08 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the faction (e.g., Brotherhood of Steel, The Minutemen).', max_length=100, unique=True)),
                ('ideology', models.TextField(blank=True, help_text='The core beliefs and goals of the faction.')),
                ('leader', models.CharField(blank=True, help_text='The current leader of the faction.', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text="The faction's logo or insignia.", null=True, upload_to='logos/factions/')),
                ('is_joinable', models.BooleanField(default=False, help_text='Can the player join this faction?')),
                ('tech_level', models.CharField(choices=[('SCAVENGED', 'Scavenged'), ('PRE_WAR', 'Pre-War'), ('ADVANCED', 'Advanced'), ('CUTTING_EDGE', 'Cutting-Edge')], default='SCAVENGED', help_text='The technological level of the faction.', max_length=20)),
                ('hostility_status', models.CharField(choices=[('FRIENDLY', 'Friendly'), ('NEUTRAL', 'Neutral'), ('HOSTILE', 'Hostile')], default='NEUTRAL', help_text='Default hostility towards the player.', max_length=20)),
                ('wiki_url', models.URLField(blank=True, help_text="URL to the faction's page on a Fallout wiki.")),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the region (e.g., Commonwealth, Nuka-World)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the region based on Fallout lore.')),
                ('map_image', models.ImageField(blank=True, help_text='A map image of the region.', null=True, upload_to='maps/regions/')),
                ('radiation_level', models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('SEVERE', 'Severe')], default='LOW', help_text='Average background radiation level.', max_length=10)),
                ('weather_pattern', models.CharField(blank=True, help_text='Common weather patterns (e.g., Clear, Radioactive Storms, Rain).', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The internal console command code for the location (e.g., AbernathyFarmExt).', max_length=100, unique=True)),
                ('name_cn', models.CharField(help_text='The Chinese name of the location (e.g., 阿柏纳西农场).', max_length=255)),
                ('notes', models.CharField(blank=True, help_text='Original notes from the provided list (e.g., 外部, 内部).', max_length=255)),
                ('parent_location_group', models.CharField(blank=True, help_text='A simple grouping key, usually the shared Chinese name for a location with multiple cells (e.g., 豆子镇酿酒厂).', max_length=255)),
                ('location_type', models.CharField(choices=[('EXT', 'Exterior'), ('INT', 'Interior'), ('DGN', 'Dungeon'), ('SET', 'Settlement'), ('VLT', 'Vault'), ('LMK', 'Landmark'), ('TEST', 'Test Cell')], default='LMK', max_length=10)),
                ('description', models.TextField(blank=True, help_text='A more detailed description of what can be found at this location.')),
                ('is_settlement', models.BooleanField(default=False, help_text='Can this location be turned into a player settlement?')),
                ('has_workbench', models.BooleanField(default=False, help_text='Does this location have a workshop workbench?')),
                ('is_cleared', models.BooleanField(default=False, help_text='Has the player cleared this location of initial enemies?')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, help_text='Estimated enemy difficulty on a scale of 1-10.')),
                ('notable_loot', models.TextField(blank=True, help_text='Notable loot, items, or characters found here.')),
                ('screenshot', models.ImageField(blank=True, help_text='An in-game screenshot of the location.', null=True, upload_to='screenshots/locations/')),
                ('controlling_faction', models.ForeignKey(blank=True, help_text='The faction that currently controls this location.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_locations', to='fallout_db.faction')),
                ('region', models.ForeignKey(blank=True, help_text='The broader region this location is in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='fallout_db.region')),
            ],
            options={
                'ordering': ['region', 'parent_location_group', 'name_cn'],
            },
        ),
    ]
