# Generated by Django 5.2.11 on 2026-02-08 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallout_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faction',
            options={'verbose_name': '派系', 'verbose_name_plural': '派系'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['region', 'parent_location_group', 'name_cn'], 'verbose_name': '地点', 'verbose_name_plural': '地点'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': '区域', 'verbose_name_plural': '区域'},
        ),
        migrations.RemoveField(
            model_name='faction',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='location',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='region',
            name='map_image',
        ),
        migrations.AddField(
            model_name='faction',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='派系Logo链接'),
        ),
        migrations.AddField(
            model_name='location',
            name='screenshot_url',
            field=models.URLField(blank=True, verbose_name='游戏截图链接'),
        ),
        migrations.AddField(
            model_name='region',
            name='map_image_url',
            field=models.URLField(blank=True, verbose_name='地图图片链接'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='hostility_status',
            field=models.CharField(choices=[('FRIENDLY', '友好'), ('NEUTRAL', '中立'), ('HOSTILE', '敌对')], default='NEUTRAL', max_length=20, verbose_name='敌对状态'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='ideology',
            field=models.TextField(blank=True, verbose_name='意识形态'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='is_joinable',
            field=models.BooleanField(default=False, verbose_name='可否加入'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='leader',
            field=models.CharField(blank=True, max_length=100, verbose_name='领袖'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='派系名称'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='tech_level',
            field=models.CharField(choices=[('SCAVENGED', '拾荒'), ('PRE_WAR', '战前'), ('ADVANCED', '先进'), ('CUTTING_EDGE', '尖端')], default='SCAVENGED', max_length=20, verbose_name='科技水平'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='wiki_url',
            field=models.URLField(blank=True, verbose_name='Wiki链接'),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='地点代码'),
        ),
        migrations.AlterField(
            model_name='location',
            name='controlling_faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_locations', to='fallout_db.faction', verbose_name='控制派系'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='location',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='难度'),
        ),
        migrations.AlterField(
            model_name='location',
            name='has_workbench',
            field=models.BooleanField(default=False, verbose_name='有无工房'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_cleared',
            field=models.BooleanField(default=False, verbose_name='是否已肃清'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_settlement',
            field=models.BooleanField(default=False, verbose_name='可否作为聚落'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('EXT', '外部'), ('INT', '内部'), ('DGN', '地下城'), ('SET', '聚落'), ('VLT', '避难所'), ('LMK', '地标'), ('TEST', '测试单元')], default='LMK', max_length=10, verbose_name='地点类型'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name_cn',
            field=models.CharField(max_length=255, verbose_name='中文名称'),
        ),
        migrations.AlterField(
            model_name='location',
            name='notable_loot',
            field=models.TextField(blank=True, verbose_name='知名战利品'),
        ),
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='原始备注'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent_location_group',
            field=models.CharField(blank=True, max_length=255, verbose_name='地点分组'),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='fallout_db.region', verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='区域名称'),
        ),
        migrations.AlterField(
            model_name='region',
            name='radiation_level',
            field=models.CharField(choices=[('NONE', '无'), ('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高'), ('SEVERE', '严重')], default='LOW', max_length=10, verbose_name='辐射水平'),
        ),
        migrations.AlterField(
            model_name='region',
            name='weather_pattern',
            field=models.CharField(blank=True, max_length=100, verbose_name='天气模式'),
        ),
    ]
