# Generated by Django 5.2.11 on 2026-02-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallout_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='wiki_url',
            field=models.URLField(blank=True, null=True, verbose_name='Wiki链接'),
        ),
        migrations.AddField(
            model_name='creature',
            name='wiki_url',
            field=models.URLField(blank=True, null=True, verbose_name='Wiki链接'),
        ),
        migrations.AddField(
            model_name='region',
            name='wiki_url',
            field=models.URLField(blank=True, null=True, verbose_name='Wiki链接'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='wiki_url',
            field=models.URLField(blank=True, null=True, verbose_name='Wiki链接'),
        ),
    ]
