# Generated by Django 5.2.11 on 2026-02-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallout_db', '0002_alter_faction_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='allies',
            field=models.CharField(blank=True, help_text='Comma-separated list of friendly factions.', max_length=255, verbose_name='盟友'),
        ),
        migrations.AddField(
            model_name='faction',
            name='base_of_operations',
            field=models.CharField(blank=True, help_text='The name of their primary headquarters.', max_length=100, verbose_name='行动基地'),
        ),
        migrations.AddField(
            model_name='faction',
            name='enemies',
            field=models.CharField(blank=True, help_text='Comma-separated list of hostile factions.', max_length=255, verbose_name='敌人'),
        ),
        migrations.AddField(
            model_name='faction',
            name='equipment_standard',
            field=models.CharField(blank=True, help_text='e.g., Pipe Weapons, Laser Rifles, Advanced Power Armor.', max_length=100, verbose_name='装备标准'),
        ),
        migrations.AddField(
            model_name='faction',
            name='faction_size',
            field=models.CharField(blank=True, help_text='e.g., Small Cell, Regional Power, Widespread.', max_length=100, verbose_name='派系规模'),
        ),
        migrations.AddField(
            model_name='faction',
            name='founding_year',
            field=models.IntegerField(blank=True, help_text='Estimated year the faction was founded.', null=True, verbose_name='成立年份'),
        ),
        migrations.AddField(
            model_name='faction',
            name='notable_members',
            field=models.TextField(blank=True, help_text='Comma-separated list of key NPCs in the faction.', verbose_name='知名成员'),
        ),
        migrations.AddField(
            model_name='faction',
            name='player_rep_impact',
            field=models.TextField(blank=True, help_text='How player actions affect reputation with this faction.', verbose_name='玩家声望影响'),
        ),
        migrations.AddField(
            model_name='faction',
            name='quote',
            field=models.TextField(blank=True, help_text="An iconic quote representing the faction's ideals.", verbose_name='标志性引言'),
        ),
        migrations.AddField(
            model_name='faction',
            name='recruitment_policy',
            field=models.CharField(blank=True, help_text='e.g., Open, Selective, Synth Only.', max_length=100, verbose_name='招募政策'),
        ),
        migrations.AddField(
            model_name='location',
            name='access_requires',
            field=models.CharField(blank=True, help_text='e.g., None, Hacking (Master), Lockpicking (Advanced).', max_length=100, verbose_name='进入需求'),
        ),
        migrations.AddField(
            model_name='location',
            name='has_chemistry_station',
            field=models.BooleanField(default=False, verbose_name='有无化学工作台'),
        ),
        migrations.AddField(
            model_name='location',
            name='has_cooking_station',
            field=models.BooleanField(default=False, verbose_name='有无烹饪站'),
        ),
        migrations.AddField(
            model_name='location',
            name='has_power_armor_station',
            field=models.BooleanField(default=False, verbose_name='有无动力装甲站'),
        ),
        migrations.AddField(
            model_name='location',
            name='interior_cell_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of interior cells/levels for this location.', verbose_name='内部单元数量'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_underwater',
            field=models.BooleanField(default=False, verbose_name='是否水下'),
        ),
        migrations.AddField(
            model_name='location',
            name='primary_enemies',
            field=models.CharField(blank=True, help_text='Main enemy type found inside.', max_length=100, verbose_name='主要敌人类型'),
        ),
        migrations.AddField(
            model_name='location',
            name='quest_starter',
            field=models.BooleanField(default=False, help_text='Does a significant quest start at this location?', verbose_name='任务起点'),
        ),
        migrations.AddField(
            model_name='location',
            name='related_quests',
            field=models.TextField(blank=True, help_text='Comma-separated list of quests involving this location.', verbose_name='相关任务'),
        ),
        migrations.AddField(
            model_name='location',
            name='respawn_rate',
            field=models.CharField(blank=True, help_text='e.g., Never, Fast (3 days), Slow (20 days).', max_length=50, verbose_name='重生速率'),
        ),
        migrations.AddField(
            model_name='region',
            name='connectivity',
            field=models.CharField(blank=True, help_text='How it connects to other regions.', max_length=100, verbose_name='连通性'),
        ),
        migrations.AddField(
            model_name='region',
            name='discovered_date',
            field=models.CharField(blank=True, help_text='Estimated date the Sole Survivor entered the area.', max_length=50, verbose_name='发现日期'),
        ),
        migrations.AddField(
            model_name='region',
            name='economic_activity',
            field=models.CharField(blank=True, help_text='e.g., Scavenging, Farming, Trade Hub.', max_length=100, verbose_name='经济活动'),
        ),
        migrations.AddField(
            model_name='region',
            name='lore_entry',
            field=models.TextField(blank=True, help_text="A short, flavorful paragraph about the region's history post-war.", verbose_name='背景故事'),
        ),
        migrations.AddField(
            model_name='region',
            name='major_landmarks',
            field=models.TextField(blank=True, help_text='Comma-separated list of key places within the region.', verbose_name='主要地标'),
        ),
        migrations.AddField(
            model_name='region',
            name='map_coordinates',
            field=models.CharField(blank=True, help_text='Grid coordinates on the in-game map, e.g., A-3.', max_length=10, verbose_name='地图坐标'),
        ),
        migrations.AddField(
            model_name='region',
            name='number_of_settlements',
            field=models.PositiveIntegerField(default=0, help_text='Number of potential player settlements.', verbose_name='聚落数量'),
        ),
        migrations.AddField(
            model_name='region',
            name='pre_war_purpose',
            field=models.CharField(blank=True, help_text="The region's purpose before the Great War.", max_length=200, verbose_name='战前用途'),
        ),
        migrations.AddField(
            model_name='region',
            name='primary_threat',
            field=models.CharField(blank=True, help_text='Main dominant enemy type in the region.', max_length=100, verbose_name='主要威胁'),
        ),
        migrations.AddField(
            model_name='region',
            name='water_source',
            field=models.CharField(blank=True, help_text='e.g., Contaminated, Potable, None.', max_length=100, verbose_name='水源状况'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='logo_url',
            field=models.URLField(blank=True, max_length=4096, verbose_name='派系Logo链接'),
        ),
        migrations.AlterField(
            model_name='location',
            name='screenshot_url',
            field=models.URLField(blank=True, max_length=8192, verbose_name='游戏截图链接'),
        ),
        migrations.AlterField(
            model_name='region',
            name='map_image_url',
            field=models.URLField(blank=True, max_length=4096, verbose_name='地图图片链接'),
        ),
    ]
