# Generated by Django 5.2.11 on 2026-02-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallout_db', '0003_faction_allies_faction_base_of_operations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='explanation',
            field=models.TextField(blank=True, help_text='Detailed background story, at least 500 characters.', verbose_name='说明'),
        ),
        migrations.AddField(
            model_name='location',
            name='explanation',
            field=models.TextField(blank=True, help_text='Detailed background story, at least 500 characters.', verbose_name='说明'),
        ),
        migrations.AddField(
            model_name='region',
            name='explanation',
            field=models.TextField(blank=True, help_text='Detailed background story, at least 500 characters.', verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='allies',
            field=models.CharField(blank=True, max_length=255, verbose_name='盟友'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='base_of_operations',
            field=models.CharField(blank=True, max_length=100, verbose_name='行动基地'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='enemies',
            field=models.CharField(blank=True, max_length=255, verbose_name='敌人'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='equipment_standard',
            field=models.CharField(blank=True, max_length=100, verbose_name='装备标准'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='faction_size',
            field=models.CharField(blank=True, max_length=100, verbose_name='派系规模'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='founding_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='成立年份'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='notable_members',
            field=models.TextField(blank=True, verbose_name='知名成员'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='player_rep_impact',
            field=models.TextField(blank=True, verbose_name='玩家声望影响'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='quote',
            field=models.TextField(blank=True, verbose_name='标志性引言'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='recruitment_policy',
            field=models.CharField(blank=True, max_length=100, verbose_name='招募政策'),
        ),
        migrations.AlterField(
            model_name='location',
            name='access_requires',
            field=models.CharField(blank=True, max_length=100, verbose_name='进入需求'),
        ),
        migrations.AlterField(
            model_name='location',
            name='interior_cell_count',
            field=models.PositiveIntegerField(default=1, verbose_name='内部单元数量'),
        ),
        migrations.AlterField(
            model_name='location',
            name='primary_enemies',
            field=models.CharField(blank=True, max_length=100, verbose_name='主要敌人类型'),
        ),
        migrations.AlterField(
            model_name='location',
            name='quest_starter',
            field=models.BooleanField(default=False, verbose_name='任务起点'),
        ),
        migrations.AlterField(
            model_name='location',
            name='related_quests',
            field=models.TextField(blank=True, verbose_name='相关任务'),
        ),
        migrations.AlterField(
            model_name='location',
            name='respawn_rate',
            field=models.CharField(blank=True, max_length=50, verbose_name='重生速率'),
        ),
        migrations.AlterField(
            model_name='region',
            name='connectivity',
            field=models.CharField(blank=True, max_length=100, verbose_name='连通性'),
        ),
        migrations.AlterField(
            model_name='region',
            name='discovered_date',
            field=models.CharField(blank=True, max_length=50, verbose_name='发现日期'),
        ),
        migrations.AlterField(
            model_name='region',
            name='economic_activity',
            field=models.CharField(blank=True, max_length=100, verbose_name='经济活动'),
        ),
        migrations.AlterField(
            model_name='region',
            name='lore_entry',
            field=models.TextField(blank=True, verbose_name='背景故事'),
        ),
        migrations.AlterField(
            model_name='region',
            name='major_landmarks',
            field=models.TextField(blank=True, verbose_name='主要地标'),
        ),
        migrations.AlterField(
            model_name='region',
            name='map_coordinates',
            field=models.CharField(blank=True, max_length=10, verbose_name='地图坐标'),
        ),
        migrations.AlterField(
            model_name='region',
            name='number_of_settlements',
            field=models.PositiveIntegerField(default=0, verbose_name='聚落数量'),
        ),
        migrations.AlterField(
            model_name='region',
            name='pre_war_purpose',
            field=models.CharField(blank=True, max_length=200, verbose_name='战前用途'),
        ),
        migrations.AlterField(
            model_name='region',
            name='primary_threat',
            field=models.CharField(blank=True, max_length=100, verbose_name='主要威胁'),
        ),
        migrations.AlterField(
            model_name='region',
            name='water_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='水源状况'),
        ),
    ]
