# Generated by Django 5.2.11 on 2026-02-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallout_db', '0004_faction_explanation_location_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='image_url_2',
            field=models.URLField(blank=True, max_length=4096, verbose_name='附加图片2链接'),
        ),
        migrations.AddField(
            model_name='faction',
            name='image_url_3',
            field=models.URLField(blank=True, max_length=4096, verbose_name='附加图片3链接'),
        ),
        migrations.AddField(
            model_name='faction',
            name='image_url_4',
            field=models.URLField(blank=True, max_length=4096, verbose_name='附加图片4链接'),
        ),
    ]
