# Generated by Django 5.2.11 on 2026-02-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallout_db', '0005_faction_image_url_2_faction_image_url_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='atmosphere_lore',
            field=models.TextField(blank=True, verbose_name='深度档案'),
        ),
        migrations.AddField(
            model_name='location',
            name='location_wiki_url',
            field=models.URLField(blank=True, verbose_name='地点Wiki链接'),
        ),
        migrations.AddField(
            model_name='location',
            name='visuals_desc',
            field=models.TextField(blank=True, verbose_name='视觉分镜'),
        ),
        migrations.AlterField(
            model_name='location',
            name='explanation',
            field=models.TextField(blank=True, help_text='Detailed background story.', verbose_name='说明'),
        ),
    ]
