"""
Django settings for fallout_project project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mivzzj5p7x)79kr-x&)7@e#)3jr&oxkn0mh5urqq+!#3y**m6)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fallout_db',
    'fallout_wiki',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fallout_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fallout_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (User-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- Django Unfold Configuration ---
UNFOLD = {
    "SITE_TITLE": "Pip-Boy 3000 Mk IV - Admin",
    "SITE_HEADER": "Pip-Boy 3000 Mk IV Administration",
    "SITE_SYMBOL": "settings",  # A simple gear icon for now
    
    # Custom "Fallout" theme colors
    "THEME": "dark", # Default to dark mode
    "STYLES": [
        "https://fonts.googleapis.com/css2?family=VT323&display=swap", # Pip-Boy font
    ],
    "COLORS": {
        "primary": {
            "50": "#eefdf0",
            "100": "#dcfbe3",
            "200": "#bbf7c8",
            "300": "#85ef9e",
            "400": "#4be071",
            "500": "#2dc957", # Pip-Boy Green
            "600": "#20a546",
            "700": "#1c823a",
            "800": "#196731",
            "900": "#16552a",
            "950": "#0a2f16"
        }
    },
    
    "DASHBOARD_CALLBACK": "fallout_db.dashboard.dashboard_callback",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False, # Set to False to use our custom navigation
        "navigation": [ # Replaced with hardcoded list of dicts
            {
                "title": "主要服务 Area",
                "items": [
                    {
                        "title": "地点管理",
                        "icon": "location_on",
                        "link": "admin:fallout_db_location_changelist", # admin:<app_label>_<model_name>_changelist
                    },
                    {
                        "title": "区域管理",
                        "icon": "map",
                        "link": "admin:fallout_db_region_changelist",
                    },
                ],
            },
            {
                "title": "人与势力",
                "items": [
                    {
                        "title": "派系管理",
                        "icon": "group",
                        "link": "admin:fallout_db_faction_changelist",
                    },
                    {
                        "title": "生物管理",
                        "icon": "bug_report",
                        "link": "admin:fallout_db_creature_changelist",
                    },
                ],
            },
            {
                "title": "物品与消耗品",
                "items": [
                    {
                        "title": "消耗品管理",
                        "icon": "local_drink",
                        "link": "admin:fallout_db_consumable_changelist",
                    },
                ],
            },
            { # This is the "查看站点" link
                "title": "查看站点",
                "icon": "launch",
                "link": "/", # Link to the main wiki site
                "target": "_blank", # Open in a new tab
            },
        ]
    }
}
